import numpy as np
#1.温度统计
temp=np.array([30,29,31,32,32,27,28])
print('平均气温',end='')
print("%3.2f" %np.mean(temp))
print(f"最高气温为{np.max(temp)}")
print(f"最低气温为{np.min(temp)}")
print(len(temp[temp>30]))#统计几天高于三十度
#2.学生成绩统计
score=np.array([85,90,78,92,88])
print('平均分是%2.1f'%np.mean(score))
print('中位数',np.median(score))
print(f'标准差是{np.std(score)}')
#3.矩阵运算
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)
#4.随机数据生成
np.random.seed(0)
num=np.random.randint(0,10,(3,4))
print(num)
print('每列的最大值',np.max(num,axis=0))
print('每行的最小值',np.min(num,axis=1))#ax表示轴axis=0表示按列来取，axis=1表示按行来取
print(np.where(num%2==1,-1,num))
#5.数组变形
arr=np.arange(1,13)
print(arr)
arr=(np.reshape(arr,(3,4)))
print(arr)
#计算每行的和
print('每行的和',np.sum(arr,axis=1))
print('每列的和',np.sum(arr,axis=0))
print('每行的平均值',np.mean(arr,axis=1))
print(np.reshape(arr,(12)))#变回原矩阵
#6.统计函数的应用
money=np.array([120,135,110,125,130,140])
print('总和',np.sum(money))
print('平均',np.mean(money))
print('方差',np.var(money))
print('最高的月份',np.argmax(money))#加上arg前缀得到索引
print('最低的月份',np.argmin(money))
#7.数组拼接
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.concatenate((A,B))#不能直接加
print(C)
print(np.reshape(C,(2,3)))
#8.唯一值与排序
arr=np.array([2,1,3,2,1,4,3])
print(np.unique(arr))#unique函数可以有两个返回值
uarr,counts=np.unique(arr,return_counts=True)
print(uarr)
print(counts)
#9.综合练习
money=np.array([20,25,22,30,28])
a=np.array([15,18,16,22,20])
print('每天的利润',money-a)
b=money-a
print('利润的标准差',np.std(b))
print('利润的平均值',np.mean(b))
print('利润最高的一天',np.argmax(b))
